export const solutions = {
  "alg-e01":[{title:"Read",explanation:"x + 3 = 8. A number plus 3 equals 8.",math:"x + 3 = 8"},{title:"What's done to x?",explanation:"3 is added. Undo by subtracting 3 from both sides.",math:"x + 3 − 3 = 8 − 3",tip:"Balance rule: same operation on both sides"},{title:"Simplify",explanation:"3−3 cancels. 8−3=5.",math:"x = 5"},{title:"Check",explanation:"Put 5 back in.",math:"5 + 3 = 8 ✓"}],
  "alg-m01":[{title:"Read",explanation:"2x + 3 = 11. Two things done to x: ×2 then +3.",math:"2x + 3 = 11"},{title:"Undo +3 first",explanation:"Last operation first. Subtract 3 from both sides.",math:"2x = 8",tip:"Always undo the last thing first — like peeling an onion"},{title:"Undo ×2",explanation:"Divide both sides by 2.",math:"x = 4"},{title:"Check",explanation:"2(4)+3=11 ✓",math:"2(4) + 3 = 11 ✓"}],
  "rnd-e01":[{title:"Find the tenths place",explanation:"6.84 — tenths is the FIRST digit after decimal: 8",math:"6 . [8] 4"},{title:"Look one place right",explanation:"The digit to the right of tenths is hundredths: 4",math:"6 . 8 [4]",tip:"Hundredths=4, which is less than 5"},{title:"Round down",explanation:"Since 4 < 5, keep the tenths digit the same (8).",math:"6.8 ✓"},{title:"Why NOT 10?",explanation:"'Tenth' = 0.1 place. 'Ten' = 10s place. They are completely different!",math:"6.8 (nearest TENTH) vs 10 (nearest TEN)"}],
  "sa-m02":[{title:"Identify dimensions",explanation:"Box: l=5in, w=3in, h=6in. Three different measurements.",math:"l=5, w=3, h=6"},{title:"Calculate 3 face areas",explanation:"Each of the 3 pairs of faces has a unique area.",math:"lw=5×3=15, lh=5×6=30, wh=3×6=18"},{title:"Add them",explanation:"Sum the three face areas.",math:"15+30+18=63"},{title:"Multiply by 2",explanation:"Every face has an identical opposite. So multiply by 2.",math:"SA = 2×63 = 126 in²",tip:"Don't forget the ×2! There are 6 faces, not 3."}],
  "func-e01":[{title:"Read the machine",explanation:"Rules are: cube first, then add 2. Apply in order.",math:"Input → [cube] → [+2] → Output"},{title:"Apply rule 1: cube",explanation:"4³ means 4×4×4, NOT 4×3.",math:"4³ = 4×4×4 = 64",tip:"Cubing is NOT the same as multiplying by 3!"},{title:"Apply rule 2: +2",explanation:"Add 2 to the result.",math:"64 + 2 = 66"},{title:"Answer",explanation:"Output = 66. Tanusree got this right in her Term 3 test!",math:"66 ✓"}],
  "int-m01":[{title:"Identify the signs",explanation:"-6 × -4. Both are negative — same signs.",math:"-6 × -4"},{title:"Apply sign rule",explanation:"Same signs → positive result.",math:"Same signs = positive ✓"},{title:"Multiply the numbers",explanation:"6 × 4 = 24. Apply positive sign.",math:"6 × 4 = 24"},{title:"Answer",explanation:"-6 × -4 = +24",math:"+24 ✓",tip:"Negative × Negative = Positive. Always!"}],
  "g7ri-e01":[{title:"What does 'rational' mean?",explanation:"A number is rational if it CAN be written as a fraction of two whole numbers (a/b).",math:"0.5 = ?"},{title:"Try to write it as a fraction",explanation:"0.5 means 5 tenths.",math:"0.5 = 5/10"},{title:"Simplify",explanation:"Divide top and bottom by 5.",math:"5/10 = 1/2"},{title:"Answer",explanation:"Since 0.5 successfully became a fraction of whole numbers, it's rational.",math:"0.5 = 1/2 → Rational ✓"}],
  "g7ri-e02":[{title:"Look inside the root",explanation:"√9 asks: what number times itself gives 9?",math:"√9 = ?"},{title:"Check for a perfect square",explanation:"9 = 3×3, so 9 is a perfect square.",math:"3×3=9 ✓"},{title:"Take the root",explanation:"Since 9 is a perfect square, its root is a whole number.",math:"√9 = 3"},{title:"Answer",explanation:"3 is a whole number, and every whole number is rational (3=3/1).",math:"√9 = 3 → Rational ✓",tip:"√(perfect square) is ALWAYS rational."}],
  "g7ri-e03":[{title:"Look inside the root",explanation:"√5 asks: what number times itself gives 5?",math:"√5 = ?"},{title:"Check for a perfect square",explanation:"List perfect squares: 1,4,9,16... 5 isn't in this list.",math:"4 < 5 < 9, no whole number squares to 5"},{title:"What happens when it's not a perfect square?",explanation:"The decimal goes on forever with no repeating pattern.",math:"√5 = 2.2360679...(never repeats)"},{title:"Answer",explanation:"A decimal that never ends and never repeats is irrational.",math:"√5 → Irrational ✓",tip:"√(non-perfect square) is ALWAYS irrational."}],
  "g7ri-e04":[{title:"Can -7 become a fraction?",explanation:"Every whole number, including negatives, can be written over 1.",math:"-7 = -7/1"},{title:"Check the definition",explanation:"A fraction of two whole numbers (a/b) — this qualifies.",math:"-7/1 is a valid fraction"},{title:"Answer",explanation:"-7 successfully fits the a/b pattern, so it's rational.",math:"-7 → Rational ✓",tip:"ALL whole numbers, positive or negative, are rational."}],
  "g7ri-e05":[{title:"Look at the decimal pattern",explanation:"0.333... — the digit 3 repeats forever without stopping.",math:"1/3 = 0.333..."},{title:"Does 'never-ending' automatically mean irrational?",explanation:"No! Check if there's a repeating PATTERN, not just whether it ends.",math:"Pattern: 3,3,3,3... (repeats)"},{title:"Repeating decimals ARE fractions",explanation:"0.333... can be written exactly as 1/3 — that's the whole point of a repeating pattern.",math:"0.333... = 1/3 exactly"},{title:"Answer",explanation:"Since it equals an exact fraction, it's rational — despite never terminating.",math:"0.333... → Rational ✓",tip:"Recurring ≠ irrational. Only NON-repeating, never-ending decimals are irrational."}],
  "g7ri-e06":[{title:"Look at π's decimal",explanation:"π = 3.14159265358979...",math:"π = 3.14159265..."},{title:"Search for a repeating pattern",explanation:"Mathematicians have calculated trillions of digits of π — no pattern has ever been found.",math:"No block of digits repeats, ever"},{title:"Compare to rational decimals",explanation:"Rational decimals either stop (0.75) or repeat a pattern (0.333...). π does neither.",math:"π: no stop, no repeat"},{title:"Answer",explanation:"π is one of the most famous irrational numbers.",math:"π → Irrational ✓"}],
  "g7ri-e07":[{title:"Look inside the root",explanation:"√16 asks: what number times itself gives 16?",math:"√16 = ?"},{title:"Check for a perfect square",explanation:"4×4=16, so 16 is a perfect square.",math:"4×4=16 ✓"},{title:"Take the root",explanation:"√16 = 4, a whole number.",math:"√16 = 4"},{title:"Answer",explanation:"4 is a whole number, so it's rational.",math:"√16 → Rational ✓"}],
  "g7ri-e08":[{title:"Can 2.75 become a fraction?",explanation:"2.75 means 2 and 75 hundredths.",math:"2.75 = 275/100"},{title:"Simplify",explanation:"Divide top and bottom by 25.",math:"275/100 = 11/4"},{title:"Check the definition",explanation:"11/4 is a fraction of two whole numbers.",math:"11/4 is valid"},{title:"Answer",explanation:"Since 2.75 became an exact fraction, it's rational.",math:"2.75 → Rational ✓",tip:"Any decimal that STOPS is always rational."}],
  "g7ri-m01":[{title:"Check all four options",explanation:"√36, √50, 0.25, -3/4 — test each one.",math:"Which is irrational?"},{title:"Test √36",explanation:"6×6=36, a perfect square.",math:"√36=6 → Rational"},{title:"Test √50",explanation:"Nearest perfect squares are 49(7²) and 64(8²). 50 isn't a perfect square.",math:"7²=49, 8²=64, 50 is between — not a perfect square"},{title:"Answer",explanation:"√50 doesn't simplify to a whole number, so it's irrational. (0.25 and -3/4 are already valid fractions, so rational.)",math:"√50 → Irrational ✓"}],
  "g7ri-m02":[{title:"Find nearby perfect squares",explanation:"List perfect squares near 20: 16(4²) and 25(5²).",math:"4²=16, 5²=25"},{title:"Where does 20 fit?",explanation:"20 is between 16 and 25.",math:"16 < 20 < 25"},{title:"Apply the same logic to the roots",explanation:"If 16<20<25, then √16<√20<√25.",math:"4 < √20 < 5"},{title:"Answer",explanation:"√20 lies between the whole numbers 4 and 5.",math:"√20 is between 4 and 5 ✓",tip:"This trick works for estimating ANY non-perfect-square root."}],
  "g7ri-m03":[{title:"Check each set for square roots",explanation:"Only one set has a square root in it: 2, 0.5, -3/4, √9.",math:"Look at √9 specifically"},{title:"Test that root",explanation:"√9=3, a perfect square root.",math:"√9 = 3 (rational)"},{title:"Check the rest of that set",explanation:"2, 0.5, -3/4 are already whole numbers/fractions — automatically rational.",math:"All four are rational"},{title:"Answer",explanation:"This is the only set where every member is confirmed rational.",math:"{2, 0.5, -3/4, √9} → all Rational ✓",tip:"The other sets each contain at least one non-perfect-square root, making them irrational."}],
  "g7ri-h01":[{title:"Simplify each root separately first",explanation:"Never assume — always simplify roots before judging the sum.",math:"√4 + √9 = ?"},{title:"Simplify √4",explanation:"2×2=4, a perfect square.",math:"√4 = 2"},{title:"Simplify √9",explanation:"3×3=9, a perfect square.",math:"√9 = 3"},{title:"Add and answer",explanation:"2+3=5, a whole number.",math:"2 + 3 = 5 → Rational ✓",tip:"A sum of two rationals is always rational — but only check this AFTER simplifying each root."}],
  "g7ri-h02":[{title:"Try to simplify each root",explanation:"Check if 2 or 3 are perfect squares.",math:"√2 + √3 = ?"},{title:"Test √2",explanation:"1²=1, 2²=4. 2 sits between — not a perfect square.",math:"√2 ≈ 1.414... (irrational)"},{title:"Test √3",explanation:"1²=1, 2²=4. 3 sits between too — not a perfect square.",math:"√3 ≈ 1.732... (irrational)"},{title:"Answer",explanation:"Neither root simplifies to a whole number, and adding two irrationals like this doesn't cancel out the never-ending decimals.",math:"√2 + √3 ≈ 3.146... → Irrational ✓",tip:"This is different from √4+√9 — there, BOTH roots simplified to whole numbers first."}],
  "g7ri-h03":[{title:"Test each statement against a counterexample",explanation:"Try to find ONE case that breaks each rule.",math:"Which statement is always TRUE?"},{title:"Test 'every square root is irrational'",explanation:"√4=2, a whole number — this breaks the rule.",math:"√4=2 → rule FALSE"},{title:"Test 'every fraction is rational'",explanation:"By definition, a fraction is a/b — exactly the definition of rational. No counterexample exists.",math:"Any a/b → always rational"},{title:"Answer",explanation:"'Every fraction is rational' holds for every possible fraction — it's the only statement that's always true.",math:"'Every fraction is rational' ✓",tip:"When a question asks which statement is always true, hunt for the one exception that breaks each wrong option."}]
};

export function generateGenericSolution(question) {
  const steps = [
    {title:"Read the question",explanation:"Identify what you are asked to find.",math:question.prompt},
    {title:"Key insight",explanation:question.hint||"Apply the relevant rule.",math:"Strategy: "+( question.hint||"use the formula")},
    {title:"Answer",explanation:"The correct answer is: "+question.answer,math:question.answer,tip:question.explanation}
  ];
  return steps;
}

export function getSolution(questionId, question) {
  if(solutions[questionId]) return solutions[questionId];
  return generateGenericSolution(question);
}
